In [4]:
import empiricaldist
import janitor
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import seaborn as sns
import sklearn.metrics
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats as ss
import session_info
from dataset_encoding import alt_encodings

In [8]:
electrolyzer_df = pd.read_csv('../Datasets/H2_O2_production.csv')
electrolyzer_df

,Unnamed: 0,Time,H2_O2_Real_Volumen_Production,H2_Real_Volumen_Production,O2_Real_Production
0,1,08:30:00,0.332963,0.22,0.110988
1,2,09:30:00,0.523560,0.35,0.174520
2,3,10:30:00,0.837989,0.56,0.279330
3,4,11:30:00,0.626043,0.42,0.208681
4,5,12:30:00,1.083424,0.72,0.361141
5,6,13:30:00,1.391466,0.93,0.463822
6,7,14:30:00,1.951854,1.30,0.650618
7,8,15:30:00,1.085384,0.72,0.361795
8,9,16:30:00,0.623182,0.42,0.207727
9,10,17:30:00,0.407997,0.27,0.135999
10,11,18:30:00,0.182715,0.12,0.060905